// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qomttkmrgwwbmvataqkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbXR0a21yZ3d3Ym12YXRhcWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODM3NjMsImV4cCI6MjA2NjM1OTc2M30.CoZahh8vovdic20cp-sUqzjfz1NRCtJRgwKGC9IJuYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);